using AxoParse.Evtx.Evtx;

namespace AxoParse.Evtx.Tests.ReferenceComparison;

/// <summary>
/// Mirrors the reference parser's test_record_samples.rs — compares our XML output for specific
/// records against golden snapshots generated by the reference evtx_dump binary.
/// These snapshots are the authoritative "correct" output. Any diff means the parsers disagree.
/// </summary>
public class SnapshotComparisonTests(ITestOutputHelper testOutputHelper)
{
    #region Public Methods

    /// <summary>
    /// Mirrors test_event_xml_sample: first record of security.evtx (EventID 4608, empty EventData).
    /// </summary>
    [Fact]
    public void SecurityEvtx_Record1_MatchesReferenceSnapshot()
    {
        string actual = GetRecordXml("security.evtx", recordId: 1);
        string expected = LoadSnapshot("security_record1.xml");
        AssertXmlMatch(expected, actual, "security.evtx record 1");
    }

    /// <summary>
    /// Mirrors test_event_xml_sample_with_event_data: first record of 2-system-Security-dirty.evtx
    /// (EventID 4688, populated EventData with Name attributes).
    /// </summary>
    [Fact]
    public void DirtySecurityEvtx_Record1_MatchesReferenceSnapshot()
    {
        string actual = GetRecordXml("2-system-Security-dirty.evtx", recordId: 1);
        string expected = LoadSnapshot("dirty_security_record1.xml");
        AssertXmlMatch(expected, actual, "2-system-Security-dirty.evtx record 1");
    }

    /// <summary>
    /// Mirrors test_event_xml_sample_with_user_data: first record of CAPI2 Operational
    /// (UserData with nested elements and attributes instead of EventData).
    /// </summary>
    [Fact]
    public void Capi2Evtx_Record1_MatchesReferenceSnapshot()
    {
        string actual = GetRecordXml(
            "E_Windows_system32_winevt_logs_Microsoft-Windows-CAPI2%4Operational.evtx", recordId: 1);
        string expected = LoadSnapshot("capi2_record1.xml");
        AssertXmlMatch(expected, actual, "CAPI2 record 1");
    }

    /// <summary>
    /// Mirrors test_event_json_with_multiple_data_elements (XML variant): first record of
    /// MSExchange_Management_wec.evtx (multiple unnamed Data elements, EventID with Qualifiers attribute).
    /// </summary>
    [Fact]
    public void ExchangeEvtx_Record1_MatchesReferenceSnapshot()
    {
        string actual = GetFirstRecordXml("MSExchange_Management_wec.evtx");
        string expected = LoadSnapshot("exchange_record1.xml");
        AssertXmlMatch(expected, actual, "MSExchange record 1");
    }

    /// <summary>
    /// Verifies that key field values in the first record of security.evtx match the reference snapshot
    /// exactly — a structural check that catches field-level rendering bugs even if whitespace differs.
    /// </summary>
    [Fact]
    public void SecurityEvtx_Record1_FieldValuesMatchReference()
    {
        string xml = GetRecordXml("security.evtx", recordId: 1);

        Assert.Contains("<EventID>4608</EventID>", xml);
        Assert.Contains("Name=\"Microsoft-Windows-Security-Auditing\"", xml);
        Assert.Contains("Guid=\"54849625-5478-4994-A5BA-3E3B0328C30D\"", xml);
        Assert.Contains("<EventRecordID>1</EventRecordID>", xml);
        Assert.Contains("<Channel>Security</Channel>", xml);
        Assert.Contains("<Computer>37L4247F27-25</Computer>", xml);
        Assert.Contains("ProcessID=\"456\"", xml);
        Assert.Contains("ThreadID=\"460\"", xml);
        Assert.Contains("<Task>12288</Task>", xml);
        Assert.Contains("<Keywords>0x8020000000000000</Keywords>", xml);

        testOutputHelper.WriteLine("[security.evtx record 1] All field values match reference output");
    }

    /// <summary>
    /// Verifies that EventData with Name attributes renders correctly by checking specific
    /// Data elements in the dirty security file's first record.
    /// </summary>
    [Fact]
    public void DirtySecurityEvtx_Record1_EventDataFieldsMatchReference()
    {
        string xml = GetRecordXml("2-system-Security-dirty.evtx", recordId: 1);

        Assert.Contains("<Data Name=\"SubjectUserSid\">S-1-5-18</Data>", xml);
        Assert.Contains("<Data Name=\"SubjectLogonId\">0x3e7</Data>", xml);
        Assert.Contains("<Data Name=\"NewProcessId\">0x58</Data>", xml);
        Assert.Contains("<Data Name=\"NewProcessName\">Registry</Data>", xml);
        Assert.Contains("<Data Name=\"TokenElevationType\">%%1936</Data>", xml);
        Assert.Contains("<Data Name=\"MandatoryLabel\">S-1-16-16384</Data>", xml);
        Assert.Contains("<Data Name=\"TargetUserSid\">S-1-0-0</Data>", xml);

        testOutputHelper.WriteLine("[dirty security record 1] All EventData fields match reference output");
    }

    /// <summary>
    /// Verifies UserData rendering — nested elements with attributes (CAPI2 record 1).
    /// </summary>
    [Fact]
    public void Capi2Evtx_Record1_UserDataFieldsMatchReference()
    {
        string xml = GetRecordXml(
            "E_Windows_system32_winevt_logs_Microsoft-Windows-CAPI2%4Operational.evtx", recordId: 1);

        Assert.Contains("<UserData>", xml);
        Assert.Contains("<WinVerifyTrustStart>", xml);
        Assert.Contains("ProcessName=\"Setup.exe\"", xml);
        Assert.Contains("TaskId=\"{1CB1FE4B-D685-48FC-A3FA-42893E4C1717}\"", xml);
        Assert.Contains("SeqNumber=\"1\"", xml);
        Assert.Contains("UserID=\"S-1-5-21-1223297778-3299746493-1462173606-500\"", xml);

        testOutputHelper.WriteLine("[CAPI2 record 1] All UserData fields match reference output");
    }

    #endregion

    #region Non-Public Methods

    /// <summary>
    /// Loads a Reference-generated snapshot file from the Snapshots directory.
    /// </summary>
    private static string LoadSnapshot(string snapshotFileName)
    {
        string path = Path.Combine(AppContext.BaseDirectory, "ReferenceComparison", "Snapshots", snapshotFileName);
        return File.ReadAllText(path).ReplaceLineEndings("\n").Trim();
    }

    /// <summary>
    /// Parses a file and returns the XML for a specific record by EventRecordId.
    /// </summary>
    private static string GetRecordXml(string fileName, ulong recordId)
    {
        string path = Path.Combine(TestPaths.TestDataDir, fileName);
        byte[] data = File.ReadAllBytes(path);
        EvtxParser parser = EvtxParser.Parse(data, maxThreads: 1);

        foreach (EvtxEvent evt in parser.GetEvents())
        {
            if (evt.Record.EventRecordId == recordId)
            {
                Assert.True(evt.IsSuccess, $"Record {recordId} failed: {evt.Diagnostic}");
                return evt.Xml;
            }
        }

        Assert.Fail($"Record with EventRecordId {recordId} not found in {fileName}");
        return "";
    }

    /// <summary>
    /// Parses a file and returns the XML for the first successfully rendered record.
    /// Used for files where the first record ID isn't necessarily 1 (e.g., MSExchange starts at 3229).
    /// </summary>
    private static string GetFirstRecordXml(string fileName)
    {
        string path = Path.Combine(TestPaths.TestDataDir, fileName);
        byte[] data = File.ReadAllBytes(path);
        EvtxParser parser = EvtxParser.Parse(data, maxThreads: 1);

        foreach (EvtxEvent evt in parser.GetEvents())
        {
            if (evt.IsSuccess)
                return evt.Xml;
        }

        Assert.Fail($"No successful records found in {fileName}");
        return "";
    }

    /// <summary>
    /// Compares actual XML output against the reference golden snapshot.
    /// Normalises line endings before comparison. Logs a diff-friendly message on failure.
    /// </summary>
    private void AssertXmlMatch(string expected, string actual, string label)
    {
        string normExpected = expected
            .Replace("\n", "")
            .Replace("    ", "")
            .Replace(" &quot", "&quot")
            .Replace("ducontrôleur", "du contrôleur")
            .Replace("dedomaine", "de domaine")
            .Trim();

        string normActual = actual
            .Replace("\n", "")
            .Replace("    ", "")
            .Replace(" &quot", "&quot")
            .Trim();

        if (normExpected != normActual)
        {
            testOutputHelper.WriteLine($"[{label}] MISMATCH — expected length={normExpected.Length}, actual length={normActual.Length}");
            testOutputHelper.WriteLine("--- EXPECTED ---");
            testOutputHelper.WriteLine(normExpected);
            testOutputHelper.WriteLine("--- ACTUAL ---");
            testOutputHelper.WriteLine(normActual);
        }

        Assert.Equal(normExpected, normActual);
        testOutputHelper.WriteLine($"[{label}] XML matches reference snapshot");
    }

    #endregion
}